name: Build ExtremeROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [o1s]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build dependencies
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh

      - name: Download source firmware if missing
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/download_fw.sh --ignore-target

      - name: Extract source firmware if missing
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh --ignore-target

      - name: Download target firmware if missing
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/download_fw.sh --ignore-source

      - name: Extract target firmware if missing
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh --ignore-source

      - name: Build ROM (incremental)
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/make_rom.sh

      - name: Upload to GoFile
        run: |
          ZIP_FILE=$(find out -maxdepth 1 -type f -name "*.zip" | head -n 1)
          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          echo "Uploaded successfully! Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'
          echo "MD5:"
          md5sum "$ZIP_FILE"
          echo "SHA256:"
          sha256sum "$ZIP_FILE"
